### ISSUE TITLE
Create MANIFEST.in

### ISSUE THREAD

**Issue by tomschr** [mschnitzer/dapsenv#1]
When using `setup.py sdist`, the script creates a tarball under `dist/`. To configure which files and directories are included, use the `MANIFEST.in` file.

See https://docs.python.org/3/distutils/sourcedist.html#specifying-the-files-to-distribute for further details.

**Comment by mschnitzer** [comment]
Implemented with https://github.com/mschnitzer/dapsenv/commit/08179b1bb4600931a967b2f01b2a93161469072d
