### ISSUE TITLE
Enhance setup.cfg with pytest section

### ISSUE THREAD

**Issue by tomschr** [mschnitzer/dapsenv#5]
I would suggest to enhance `setup.cfg` with the following lines:

```ini
[pytest]
norecursedirs = .git build .env/ env/ .tmp/
addopts = --ignore=.env/ --ignore=.tmp/ --ignore=.git/ --ignore=.tox/ 
```

That simplifies it when you run just `py.test`.

**Comment by mschnitzer** [comment]
Done in https://github.com/mschnitzer/dapsenv/commit/20d52d54e34aada9c9d91b6279411e482f1ff83c#diff-380c6a8ebbbce17d55d50ef17d3cf906R16
